coś jest nie tak, bo się nie kompiluje (jest jeden fail) - 2>C:\Users\Igor\Documents\nitrogen\ConverterDll\Converter\OpenFile.cs(5,25,5,31): error CS0234: The type or namespace name 'Office' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
Naprawcie to. :)